package com.dmnprojects.test;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class patient implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("age")
	private double age;

	@org.kie.api.definition.type.Label("pression")
	private double pression;

	public patient() {
	}

	public double getAge() {
		return this.age;
	}

	public void setAge(double age) {
		this.age = age;
	}

	public double getPression() {
		return this.pression;
	}

	public void setPression(double pression) {
		this.pression = pression;
	}

	public patient(double age, double pression) {
		this.age = age;
		this.pression = pression;
	}

}